@startuml
left to right direction

actor :Back-end API: as be
actor :Front-end: as fe
actor :Pengguna: as usr
actor :IANA\n(Internet Assigned Numbers Association): as iana
actor :Pengembang pihak ketiga: as dev

together {
  "Situs web (phantomports.com)" as (website)
  "Pelacakan port" as (search)
  "Rekomendasi port" as (recommend)
}

"Himpunan ports IANA" as (ports)
"Himpunan ports GraphQL (Authorized cache)" as (cached)

"Otorisasi" as (authorize)

(website) -- usr
fe -- (website)
(website) .> (search): <<extend>>
(search) .> (recommend): <<include>>

be -- (ports)
(ports) -- iana

be -- (authorize)
fe -- (authorize)
(authorize) -- dev

be -- (cached)
(authorize) .> (cached): <<extend>>

@enduml
